---
title: "linear_models"
output: html_document
date: '2023-11-09'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```

## Model fitting

```{r}
## some data cleaning first 
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) |> 
  filter(borough != "Staten Island") |> 
  select(price, stars, borough, neighborhood, room_type)
```

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
## can print the 'fit' to see if its what you want 
## more options for looking at 'fit' under "Tidying output"
```


```{r}
nyc_airbnb = 
  nyc_airbnb |> 
  mutate(
    borough = fct_infreq(borough),
    room_type = fct_infreq(room_type))

fit = lm(price ~ stars + borough, data = nyc_airbnb)
```

## Tidying the output 

```{r}
#summary(fit)
#summary(fit)$coef
#coef(fit)
#fitted.values(fit)

## commenting these out bc it makes the knit cleaner, these commands work and knit properly when uncommented :)

fit |> 
  broom::glance()


fit |> 
  broom::tidy()
```

```{r}
fit |> 
  broom::tidy() |> 
  select(term, estimate, p.value) |> 
  mutate(term = str_replace(term, "^borough", "Borough: ")) |> 
  knitr::kable(digits = 3)
```

## Diagnostics 

```{r}
modelr::add_residuals(nyc_airbnb, fit)
```

```{r}
modelr::add_predictions(nyc_airbnb, fit)
```

```{r}
nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  ggplot(aes(x = borough, y = resid)) + geom_violin()
```

```{r}
nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  ggplot(aes(x = stars, y = resid)) + geom_point()
```

## Hypothesis testing 

```{r}
## fitting a null and alt model 
fit_null = lm(price ~ stars + borough, data = nyc_airbnb)
fit_alt = lm(price ~ stars + borough + room_type, data = nyc_airbnb)
```

```{r}
anova(fit_null, fit_alt) |> 
  broom::tidy()
```

## Borough-level differences 

```{r}
fit = 
  nyc_airbnb |> 
  lm(price ~ stars * borough + room_type * borough, data = _)

fit |> 
  broom::tidy()
```

```{r}
airbnb_lm = function(df) {
  lm(price ~ stars + room_type, data = df)
}
nyc_airbnb |> 
  nest(df = -borough) |> 
  mutate(
    models = map(df, airbnb_lm)
  )
```

